### ISSUE TITLE
invalid size of

### ISSUE THREAD

**Issue by MyraBaba** [stereomatchingkiss/blogCodes2#6]
Hi,

When I try to compile in Qt 5.12 I have below errors:

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2395:27: error: invalid application of 'sizeof' to an incomplete type 'dlib_tool::face_detector'
            static_assert(sizeof(_Tp) > 0, "default_delete can not delete incomplete type");
                          ^~~~~~~~~~~`

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2395:27: error: invalid application of 'sizeof' to an incomplete type 'mxnet_tool::face_key_extractor'
            static_assert(sizeof(_Tp) > 0, "default_delete can not delete incomplete type");
                          ^~~~~~~~~~~`

**Comment by stereomatchingkiss** [comment]
Please the pull the codes again, should be fixed now

**Comment by MyraBaba** [comment]
Hi Thanks,

I have 👍 
`../../../../mxnet/cpp-package/include/mxnet-cpp/op_map.h:99:10: error: unknown type name 'OpHandle'
  inline OpHandle GetOpHandle(const std::string &name) {
         ^
../../../../mxnet/cpp-package/include/mxnet-cpp/op_map.h:105:25: error: use of undeclared identifier 'OpHandle'
  std::map<std::string, OpHandle> op_handles_;
                        ^
../../../../mxnet/cpp-package/include/mxnet-cpp/op_map.h:69:5: error: unknown type name 'nn_uint'; did you mean 'mx_uint'?
    nn_uint num_ops;
    ^~~~~~~
    mx_uint
../../../../mxnet/include/mxnet/c_api.h:58:22: note: 'mx_uint' declared here
typedef unsigned int mx_uint;
                     ^
In file included from ../main.cpp:2:
In file included from ../../mxnet_face_recognition/../libs/face/key/insight_face_key_extractor_params.hpp:4:
In file included from ../../../../mxnet/cpp-package/include/mxnet-cpp/MxNetCpp.h:30:
In file included from ../../../../mxnet/cpp-package/include/mxnet-cpp/executor.hpp:32:
In file included from ../../../../mxnet/cpp-package/include/mxnet-cpp/executor.h:35:
In file included from ../../../../mxnet/cpp-package/include/mxnet-cpp/symbol.h:35:
../../../../mxnet/cpp-package/include/mxnet-cpp/op_map.h:71:9: error: use of undeclared identifier 'NNListAllOpNames'; did you mean
      'MXListAllOpNames'?
`

windows to *nix always painfull.  :(

**Comment by stereomatchingkiss** [comment]
Which mxnet version you build(I am using 1.31 I think)? Do your unix os support prebuild version of mxnet?

**Comment by MyraBaba** [comment]
I have both mac osx and debian.

We are compiling from source generally. 

for the Qt pro file we prefer to use 👍 
`CONFIG  += link_pkgconfig

PKGCONFIG += opencv

PKGCONFIG += dlib-1`

**Comment by stereomatchingkiss** [comment]
how do you compile your mxnet on mac or debian?

Maybe a bug of mxnet

**Comment by MyraBaba** [comment]
Mac OS X 

We had no issue before and all the example of the money working correctly.

May I invite you to linux world :)

Let me have a cup of caffe. And start over…

What is inside your MXNET_PATH ?

Best

**Comment by MyraBaba** [comment]
Now I have : 

error: invalid application of 'sizeof' to an incomplete type 'ocv::face::dlib_cnn_face_detector'
static_assert(sizeof(_Tp) > 0, “default_delete can not delete incomplete type");

And 

 error: invalid application of 'sizeof' to an incomplete type 'face_reg_db'
static_assert(sizeof(_Tp) > 0, “default_delete can not delete incomplete type");

**Comment by stereomatchingkiss** [comment]
> We had no issue before and all the example of the money working
correctly.

weird, it looks like a cross-referencing problem to me, maybe your mxnet
include a wrong file?
I remember I manually copy some files into the include folder since the
install do not works well

> May I invite you to linux world :)

If it was a pay project, I would.
Don't have interest to make the projects support on linux or mac now

> What is inside your MXNET_PATH ?

some header files, build libs and dll, hard to list all of them out

> error: invalid application of 'sizeof' to an incomplete type
'ocv::face::dlib_cnn_face_detector'

Should fix now, please pull again

MyraBaba <notifications@github.com> 於 2019年2月24日 週日 上午6:49寫道：

**Comment by MyraBaba** [comment]
This is the .pro file:

`TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle

QT += core

DLIB_PATH = ../../3rdLibs/dlib/dlib/build/install
MXNET_PATH = /Users/pamela/Downloads/incubator-mxnet
OPENCV_PATH = ../../3rdLibs/opencv/opencv_3_4_2/opencv/build

INCLUDEPATH += ../..
INCLUDEPATH += $${BOOST_PATH}
#INCLUDEPATH += $${DLIB_PATH}/include
INCLUDEPATH += $${OPENCV_PATH}/include

INCLUDEPATH += $${MXNET_PATH}/cpp-package/include
#INCLUDEPATH += $${MXNET_PATH}/cpp-package/include/mxnet-cpp/
INCLUDEPATH += $${MXNET_PATH}/3rdparty/dmlc-core/include/
INCLUDEPATH += $${MXNET_PATH}/3rdparty/tvm/nnvm/include
INCLUDEPATH += $${MXNET_PATH}/include

INCLUDEPATH += /opt/intel/compilers_and_libraries_2018.1.126/mac/mkl/include

LIBS += $${MXNET_PATH}/lib/ -lmxnet


QT_CONFIG -= no-pkg-config
CONFIG  += link_pkgconfig
PKGCONFIG += opencv
PKGCONFIG += dlib-1

SOURCES += \
        main.cpp \
    /Users/pamela/Projects/blogCodes2/libs/mxnet/common.cpp \
    face_reg_db.cpp \
    face_recognition.cpp \            
    /Users/pamela/Projects/blogCodes2/libs/face/detect/dlib_cnn_face_detector.cpp \
    /Users/pamela/Projects/blogCodes2/libs/face/key/insight_face_key.cpp \
    /Users/pamela/Projects/blogCodes2/libs/face/key/insight_face_key_extractor.cpp \

HEADERS += \
    /Users/pamela/Projects/blogCodes2/libs/mxnet/common.hpp \
    face_reg_db.hpp \
    face_recognition.hpp \        
    face_reg_info.hpp \
    /Users/pamela/Projects/blogCodes2/libs/image_format_convert/dlib_to_array.hpp \
    /Users/pamela/Projects/blogCodes2/libs/face/detect/dlib_cnn_face_detector.hpp \
    /Users/pamela/Projects/blogCodes2/libs/face/detect/dlib_cnn_face_detector_params.hpp \
    /Users/pamela/Projects/blogCodes2/libs/face/detect/dlib_face_detector_net.hpp \
    /Users/pamela/Projects/blogCodes2/libs/face/key/insight_face_key.hpp \
    /Users/pamela/Projects/blogCodes2/libs/face/key/insight_face_key_extractor.hpp \
    /Users/pamela/Projects/blogCodes2/libs/face/key/insight_face_key_extractor_params.hpp \
    /Users/pamela/Projects/blogCodes2/libs/mxnet/generic_predictor.hpp
`

**Comment by stereomatchingkiss** [comment]
This line is more than enough

INCLUDEPATH += $${MXNET_PATH}/cpp-package/include

another include paths start with MXNET_PATH can be removed

ex :
INCLUDEPATH += $${MXNET_PATH}/3rdparty/dmlc-core/include/
INCLUDEPATH += $${MXNET_PATH}/3rdparty/tvm/nnvm/include


MyraBaba <notifications@github.com> 於 2019年2月24日 週日 下午6:10寫道：

**Comment by MyraBaba** [comment]
Hi,

When keep only  INCLUDEPATH += $${MXNET_PATH}/cpp-package/include for mxnet it gives:
> 

../../../../Downloads/incubator-mxnet/cpp-package/include/mxnet-cpp/base.h:32:10: fatal error: 'nnvm/c_api.h' file not found
#include “nnvm/c_api.h"


İf I include  INCLUDEPATH += $${MXNET_PATH}/3rdparty/tvm/nnvm/include
> 
Than Its asking:

../../../../Downloads/incubator-mxnet/cpp-package/include/mxnet-cpp/op_map.h:33:10: fatal error: 'dmlc/logging.h' file not found
#include "dmlc/logging.h"
^~~~~~~~~~~~~~~~

When I include INCLUDEPATH += $${MXNET_PATH}/3rdparty/dmlc-core/include/
> 

Than we back to our original error:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2395:27: error: invalid application of 'sizeof' to an incomplete type 'ocv::face::dlib_cnn_face_detector'
static_assert(sizeof(_Tp) > 0, "default_delete can not delete incomplete type");
^~~~~~~~~~~

**Comment by stereomatchingkiss** [comment]
Not $${MXNET_PATH}/cpp-package/include


but


INCLUDEPATH += $${MXNET_PATH}/include

After you include the files correctly, let us discuss next steps


MyraBaba <notifications@github.com> 於 2019年2月24日 週日 下午10:12寫道：

> Hi,
>
> When keep only INCLUDEPATH += $${MXNET_PATH}/cpp-package/include for mxnet
> it gives:
> >
>
> ../../../../Downloads/incubator-mxnet/cpp-package/include/mxnet-cpp/base.h:32:10:
> fatal error: 'nnvm/c_api.h' file not found
> #include “nnvm/c_api.h"
>
>
> İf I include INCLUDEPATH += $${MXNET_PATH}/3rdparty/tvm/nnvm/include
> >
> Than Its asking:
>
> ../../../../Downloads/incubator-mxnet/cpp-package/include/mxnet-cpp/op_map.h:33:10:
> fatal error: 'dmlc/logging.h' file not found
> #include "dmlc/logging.h"
> ^~~~~~~~~~~~~~~~
>
> When I include INCLUDEPATH += $${MXNET_PATH}/3rdparty/dmlc-core/include/
> >
>
> Than we back to our original error:
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2395:27:
> error: invalid application of 'sizeof' to an incomplete type
> 'ocv::face::dlib_cnn_face_detector'
> static_assert(sizeof(_Tp) > 0, "default_delete can not delete incomplete
> type");
> ^~~~~~~~~~~
>
>
>
>

**Comment by stereomatchingkiss** [comment]
Folders in the include folder

ngap wei Tham <thamngapwei@gmail.com> 於 2019年2月24日 週日 下午11:22寫道：

> Not $${MXNET_PATH}/cpp-package/include
>
>
> but
>
>
> INCLUDEPATH += $${MXNET_PATH}/include
>
> After you include the files correctly, let us discuss next steps
>
>
> MyraBaba <notifications@github.com> 於 2019年2月24日 週日 下午10:12寫道：
>
>> Hi,
>>
>> When keep only INCLUDEPATH += $${MXNET_PATH}/cpp-package/include for
>> mxnet it gives:
>> >
>>
>> ../../../../Downloads/incubator-mxnet/cpp-package/include/mxnet-cpp/base.h:32:10:
>> fatal error: 'nnvm/c_api.h' file not found
>> #include “nnvm/c_api.h"
>>
>>
>> İf I include INCLUDEPATH += $${MXNET_PATH}/3rdparty/tvm/nnvm/include
>> >
>> Than Its asking:
>>
>> ../../../../Downloads/incubator-mxnet/cpp-package/include/mxnet-cpp/op_map.h:33:10:
>> fatal error: 'dmlc/logging.h' file not found
>> #include "dmlc/logging.h"
>> ^~~~~~~~~~~~~~~~
>>
>> When I include INCLUDEPATH += $${MXNET_PATH}/3rdparty/dmlc-core/include/
>> >
>>
>> Than we back to our original error:
>> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:2395:27:
>> error: invalid application of 'sizeof' to an incomplete type
>> 'ocv::face::dlib_cnn_face_detector'
>> static_assert(sizeof(_Tp) > 0, "default_delete can not delete incomplete
>> type");
>> ^~~~~~~~~~~
>>
>>
>>
>>

**Comment by MyraBaba** [comment]
I tried many combination.

withou nnvm/include and dmlc-core/include/ . it keeps asking header files.

when I include same error : size_t

i took your time but stuck here. first time i had such crazy situation(blaming microSoft:)

**Comment by stereomatchingkiss** [comment]
I check your .pro carefully and find something weirds

1. What is the definition of BOOST_PATH?

2. MXNET_PATH should point to the install folder, I don't know what will be
if you build on linux or mac, but on windows, the mxnet project
will create an install folder and put the header files in that folder.

3. NCLUDEPATH += $${MXNET_PATH}/cpp-package/include is wrong(sorry, asked
you to use this path before), it should be NCLUDEPATH +=
$${MXNET_PATH}/include

4. Unzip the include.7z I sent you, check out how the files organize, your
compiler complain it cannot find the files. If you add too many paths,
cross-referencing problem may
popup



MyraBaba <notifications@github.com> 於 2019年2月24日 週日 下午11:45寫道：

**Comment by stereomatchingkiss** [comment]
My bad, did not remove BOOST_PATH from .pro, updated now

Anyway, thanks for your bug report

ngap wei Tham <thamngapwei@gmail.com> 於 2019年2月25日 週一 上午8:17寫道：

**Comment by MyraBaba** [comment]
Hi,

I didnt see / receive include.7z file.  did you forget to attach?

**Comment by stereomatchingkiss** [comment]
Please check you email

MyraBaba <notifications@github.com> 於 2019年2月25日 週一 下午3:16寫道：
